public enum IncomingPackets : int
{
    CONNECT_RESPONSE = 1,
    MOVEMENT_KEYS ,
    ACTION_KEYS,
    HANDLE_MAP_LOADED,
	HANDLE_LEFT_MOUSE_CLICK,
    HANDLE_TRIGGER_INTERACT,
    HANDLE_CHAT_MESSAGE,
}