public enum OutGoingPackets : int
{
    RESPOSNE_VERIFY = 1,
    MOVE_CHARACTER = 2,
    SEND_SPAWN_PLAYER = 3,
    SEND_LOGOUT = 4,
    SEND_CHARACTER_COMBAT_STAGE = 5,
    SEND_MONSTER_SPAWN = 6,
    SEND_PLAYER_LOOKAT = 7,
    SEND_DESTROY_OBJECT = 8,
}