public enum IncomingPackets : int
{
   HANDLE_LOGIN_RESPONSE = 1,
   HANDLE_MOVE_CHARACTER = 2,
   HANDLE_SPAWN_PLAYER = 3,
   HANDLE_LOGOUT = 4,
   HANDLE_TRIGGER_COMABT = 5,
   HANDLE_SPAWN_MONSTER = 6,
   HANDLE_PLAYER_LOOKAT = 7,
   HANDLE_DESTROY_OBJECT = 8,
   HANDLE_ANIMATOR_TRIGGER = 9,
   HANDLE_CHAT_MESSAGE = 10,
}   