public enum IncomingPackets : int
{
   HANDLE_LOGIN_RESPONSE = 1,
   HANDLE_MOVE_CHARACTER = 2,
   HANDLE_PLAYER_ANIMATION = 3,
   HANDLE_SPAWN_WORLD_NPCS = 4,
   HANDLE_MOVE_NPC = 5,
   HANDLE_SPAWN_PLAYER = 6,
   HANDLE_LOGOUT = 7,

}   